name: dyslexia_app
description: Dyslexia-friendly learning app
publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  flutter_tts: ^3.8.5
  google_fonts: ^6.1.0
  cupertino_icons: ^1.0.8
  image_picker: ^1.0.7
  google_mlkit_text_recognition: ^0.13.1
  google_mlkit_commons: ^0.8.1
  # record: ^5.0.4
  path_provider: ^2.1.2
  shared_preferences: ^2.2.2

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true

  assets:
    - assets/fonts/
    - assets/data/levels.json

  fonts:
    - family: null
      fonts:
        - asset: lib/assets/fonts/OpenDyslexic-Regular.otf
        - asset: assets/fonts/OpenDyslexic-Bold.otf
          weight: 700

    - family: null
      fonts:
        - asset: assets/fonts/Lexend-Regular.ttf
        - asset: assets/fonts/Lexend-Bold.ttf
          weight: 700
